### PR TITLE
Adding ability to use additional fields for volume mounts

### PR DESCRIPTION
**Pull request by trahim**

### CODE REVIEW

**Comment by charlie-haley** [comment]
Hey @trahim, sorry for the delay in looking at this! Could you add some tests into the `/tests` folder as part of this PR? You should be able to make use the existing Deployment tests - https://github.com/redpanda-data/redpanda-connect-helm-chart/blob/main/tests/deployment_test.yaml

**Comment by trahim** [comment]
Hey @charlie-haley added some in now

**Comment by charlie-haley** [comment]
Fixes https://github.com/redpanda-data/redpanda-connect-helm-chart/issues/103

**Review by charlie-haley — APPROVED** [review]
LGTM! Thanks for the PR @trahim

**Comment by bentatham** [comment]
Any chance we can get a new release to include this?  Or a timeline of when that would be coming?

**Comment by trahim** [comment]
Looking at the GH job looks like I also needed to bump up the version of the `Chart.yaml`(my bad) as a release was attempted, can create a PR bumping or leave to you @charlie-haley ?

**Comment by charlie-haley** [comment]
Hey, I'm currently chatting to Redpanda about whether the chart will be moved into their Helm Repo or stay in the benthosdev one. So I'm currently holding off on the release until then.

Worst case scenario I'll do a release early next week to the current Helm Repo.

**Comment by bentatham** [comment]
Is there any objection if I submit a PR to allow templates in the values of extraVolumes and extraVolumeMounts (using `tpl`), so we can reference other values from within the values file as part of those?  (eg use an another value for the `subPath`).

**Comment by trahim** [comment]
Any updates on a new release @charlie-haley ?

**Comment by trahim** [comment]
Any chance of getting a release here @charlie-haley ?

**Pull request merged**
